# Generated by Django 4.2 on 2023-04-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tagghist",
            name="REG_DT",
            field=models.DateTimeField(),
        ),
    ]
