# Generated by Django 4.2 on 2023-05-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_tagghist_reg_dt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tagghist",
            name="REG_DT",
        ),
    ]
